### ISSUE TITLE
Api is returning timed out error, now 502, now Hostname/IP does not match certificate's altnames: Host: x-colors.yurace.pro. is not in the cert's altnames: DNS:linkbyteit.com

### ISSUE THREAD

**Issue by DrMineword** [cheatsnake/xColors-api#11]
{
"response":"timeout of 60000ms exceeded"
}

**Comment by DrMineword** [comment]
@cheatsnake is this erre caused by user or api just died?

**Comment by hanacoon1** [comment]
@DrMineword @cheatsnake, just dropping in to say that I'm experiencing this as well. It seems like as of yesterday, or maybe over the weekend, the API stopped working (since I can confirm it was working for me last Friday).

**Comment by DrMineword** [comment]
I have somehere discord iso timestamp from time when api returned errors

**Comment by DrMineword** [comment]
@hanacoon1 i have error since 2024-10-05T04:00:02.745Z±3hours

Now api return 502, so i think something is going on to fix it

**Comment by DrMineword** [comment]
@hanacoon1 @cheatsnake 
Hostname/IP does not match certificate's altnames: Host: x-colors.yurace.pro. is not in the cert's altnames: DNS:linkbyteit.com

**Comment by cheatsnake** [comment]
@DrMineword @hanacoon1 
The server where API was working was deleted for non-payment (I paid for a year of the server and could not renew it in time). Now everything works as before. Glad someone is using my projects, sorry for the inconvenience.

**Comment by hanacoon1** [comment]
@cheatsnake aw thanks so much for your reply! Appreciate you getting things back up and running, thanks for sharing your great work with the world!
