### ISSUE TITLE
Application Error?

### ISSUE THREAD

**Issue by tkapustka** [cheatsnake/xColors-api#4]
API/site was working on Friday but now getting this error?

<img width="783" alt="Screen Shot 2022-03-27 at 2 32 30 PM" src="https://user-images.githubusercontent.com/76138093/160300760-157abca4-017d-4d47-be35-984f24b0fa21.png">

**Comment by cheatsnake** [comment]
> API/site was working on Friday but now getting this error?
> 
> <img alt="Screen Shot 2022-03-27 at 2 32 30 PM" width="783" src="https://user-images.githubusercontent.com/76138093/160300760-157abca4-017d-4d47-be35-984f24b0fa21.png">

Sorry. I have a time limit on Heroku this month. The app will go live again on 1 April. I was so surprised that so many people started using my apps.

**Comment by tkapustka** [comment]
ahh okie dokie, thank you for letting me know. Your app works great by the way, a big fan!
