### ISSUE TITLE
Requesting random colors of a specified shade returns invalid HSL color codes

### ISSUE THREAD

**Issue by KettLovahr** [cheatsnake/xColors-api#5]
When making a request such as `https://x-colors.herokuapp.com/api/random/blue?number=8&type=light` wherein a shade is specified, the response will contain invalid HSL color codes, missing the `%` sign in the lightness component, as follows:

`"hsl" : "hsl(100, 98%, 66)"`

This also happens if the specified shade is `all`, but not if nothing is specified

```
[kett] ~ curl "https://x-colors.herokuapp.com/api/random/all?number=1" 2>/dev/null | json_pp
{
   "hex" : "#03871D",
   "hsl" : "hsl(132, 98%, 53)",
   "rgb" : "rgb(3, 135, 29)"
}

[kett] ~ curl "https://x-colors.herokuapp.com/api/random?number=1" 2>/dev/null | json_pp    
{
   "hex" : "#661E06",
   "hsl" : "hsl(15, 94%, 40%)",
   "rgb" : "rgb(102, 30, 6)"
}
```

I didn't dig deep in the code, but I'm pretty sure this is all due to the missing percentage sign in the following line:

https://github.com/cheatsnake/xColors-api/blob/69227f785c1eecdb1d3a8a212e7a3284f537f91f/src/services/color.service.ts#L21

**Comment by cheatsnake** [comment]
> When making a request such as `https://x-colors.herokuapp.com/api/random/blue?number=8&type=light` wherein a shade is specified, the response will contain invalid HSL color codes, missing the `%` sign in the lightness component, as follows:
> 
> `"hsl" : "hsl(100, 98%, 66)"`
> 
> This also happens if the specified shade is `all`, but not if nothing is specified
> 
> ```
> [kett] ~ curl "https://x-colors.herokuapp.com/api/random/all?number=1" 2>/dev/null | json_pp
> {
>    "hex" : "#03871D",
>    "hsl" : "hsl(132, 98%, 53)",
>    "rgb" : "rgb(3, 135, 29)"
> }
> 
> [kett] ~ curl "https://x-colors.herokuapp.com/api/random?number=1" 2>/dev/null | json_pp    
> {
>    "hex" : "#661E06",
>    "hsl" : "hsl(15, 94%, 40%)",
>    "rgb" : "rgb(102, 30, 6)"
> }
> ```
> 
> I didn't dig deep in the code, but I'm pretty sure this is all due to the missing percentage sign in the following line:
> 
> https://github.com/cheatsnake/xColors-api/blob/69227f785c1eecdb1d3a8a212e7a3284f537f91f/src/services/color.service.ts#L21

Thank you so much for your feedback! The error has already been fixed.
