### ISSUE TITLE
Conversion to HSL is incorrect

### ISSUE THREAD

**Issue by KettLovahr** [cheatsnake/xColors-api#6]
`convertRgbToHsl` seems to output the same values a conversion to HSV/HSB would, rather than to HSL.

**Comment by cheatsnake** [comment]
> `convertRgbToHsl` seems to output the same values a conversion to HSV/HSB would, rather than to HSL.

Thank you for another response! There was a complete confusion and the conversion function did not do exactly what was expected of it. Now I have changed part of the code and checked the correctness of the conversion on third-party resources. I hope everything is working well now.
